# Dockerfile for Deadline Repository
FROM ubuntu:20.04

# Install dependencies
RUN apt-get update && apt-get install -y \
    wget \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Download the Deadline Repository installer
RUN wget https://thinkbox-installers.s3.us-west-2.amazonaws.com/Releases/Deadline/10.3/7_10.3.2.1/Deadline-10.3.2.1-linux-installers.tar \
    -O /tmp/deadline-repo-installer.run && \
    chmod +x /tmp/deadline-repo-installer.run

# Install Deadline Repository non-interactively
RUN /tmp/deadline-repo-installer.run --mode unattended --dbtype mongo \
    --dbhost mongo --dbport 27017 --dbuser admin --dbpassword password

# Expose required ports
EXPOSE 8080 4433

# Volumes for persistent storage of the repository
VOLUME ["/opt/Thinkbox/DeadlineRepository10"]

# Command to start the repository server
CMD ["/etc/init.d/deadline-repository start"]
