# Dockerfile for Deadline Repository
FROM ubuntu:20.04

# Install dependencies
RUN apt-get update && apt-get install -y \
    wget \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Download the Deadline Repository installer
# RUN wget https://thinkbox-installers.s3.us-west-2.amazonaws.com/Releases/Deadline/10.3/7_10.3.2.1/Deadline-10.3.2.1-linux-installers.tar \
#     -O /tmp/deadline-repo-installer.run && \
#     chmod +x /tmp/deadline-repo-installer.run

# Copy installer file
COPY ../DeadlineRepository-10.3.2.1-linux-x64-installer.run /tmp/deadline-repo-installer.run
RUN chmod +x /tmp/deadline-repo-installer.run

# Expose required ports
EXPOSE 8080 4433

# Volumes for persistent storage of the repository
VOLUME ["/opt/Thinkbox/DeadlineRepository10"]

# Create an entrypoint script to install the Deadline Repository at runtime
COPY ./repo/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Command to start the entrypoint script
CMD ["/entrypoint.sh"]
