services:
  db:
    build:
      dockerfile: ./db/Dockerfile
    container_name: deadline_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo_data:/data/db
    networks:
      - deadline_network
    ports:
      - "27017:27017"

  # repo:
  #   build:
  #     dockerfile: ./repo/Dockerfile
  #   container_name: deadline_repo
  #   volumes:
  #     - ./deadline_repo:/opt/Thinkbox/DeadlineRepository10
  #   depends_on:
  #     - db
  #   networks:
  #     - deadline_network
  #   ports:
  #     - "8080:8080"
  #     - "4433:4433"

  rcs:
    build:
      dockerfile: ./rcs/Dockerfile
    container_name: deadline_rcs
    volumes:
      - ./deadline_rcs:/opt/Thinkbox/Deadline10
      - ./certs:/opt/Thinkbox/Deadline10/certs  # Mount the certificate directory
    depends_on:
      - db
    networks:
      - deadline_network
    ports:
      - "4433:4433"
      - "8080:8080"

  web:
    build:
      dockerfile: ./webservice/Dockerfile
    container_name: deadline_web
    volumes:
      - ./deadline_webservice:/opt/Thinkbox/Deadline10
    depends_on:
      - repo
    networks:
      - deadline_network
    ports:
      - "8082:8082"

networks:
  deadline_network:
    driver: bridge
